# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1

jobs:
  "php82-sqlite3":
    docker:
      - image: aimeos/ci-php:8.2
        environment:
          DB_DRIVER: sqlite
    steps:
      - checkout
      - restore_cache:
          keys:
            - php82-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php82-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: ./vendor/bin/phpunit

  "php82-mariadb10":
    docker:
      - image: aimeos/ci-php:8.2
        environment:
          DB_DRIVER: mariadb
          DB_HOST: "127.0.0.1"
          DB_PORT: 3306
          DB_USERNAME: pagible
          DB_PASSWORD: pagible
          DB_DATABASE: cms
      - image: mariadb:10
        environment:
          MARIADB_ROOT_PASSWORD: rootpw
          MARIADB_USER: pagible
          MARIADB_PASSWORD: pagible
          MARIADB_DATABASE: cms
    steps:
      - checkout
      - restore_cache:
          keys:
            - php82-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php82-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: for i in `seq 1 10`; do nc -z 127.0.0.1 3306 && echo OK && exit 0; echo -n .; sleep 1; done
      - run: ./vendor/bin/phpunit

  "php82-mysql8":
    docker:
      - image: aimeos/ci-php:8.2
        environment:
          DB_DRIVER: mysql
          DB_HOST: "127.0.0.1"
          DB_PORT: 3306
          DB_USERNAME: pagible
          DB_PASSWORD: pagible
          DB_DATABASE: cms
      - image: mysql:8
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_USER: pagible
          MYSQL_PASSWORD: pagible
          MYSQL_DATABASE: cms
    steps:
      - checkout
      - restore_cache:
          keys:
            - php82-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php82-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: for i in `seq 1 10`; do nc -z 127.0.0.1 3306 && echo OK && exit 0; echo -n .; sleep 1; done
      - run: ./vendor/bin/phpunit

  "php82-pgsql14":
    docker:
      - image: aimeos/ci-php:8.2
        environment:
          DB_DRIVER: pgsql
          DB_HOST: "127.0.0.1"
          DB_PORT: 5432
          DB_USERNAME: pagible
          DB_PASSWORD: pagible
          DB_DATABASE: cms
      - image: postgres:14
        environment:
          POSTGRES_PASSWORD: pagible
          POSTGRES_USER: pagible
          POSTGRES_DB: cms
    steps:
      - checkout
      - restore_cache:
          keys:
            - php82-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php82-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: for i in `seq 1 10`; do nc -z 127.0.0.1 5432 && echo OK && exit 0; echo -n .; sleep 1; done
      - run: ./vendor/bin/phpunit

  "php82-mssql17":
    docker:
      - image: aimeos/ci-php:8.2
        environment:
          DB_DRIVER: sqlsrv
          DB_HOST: "127.0.0.1"
          DB_PORT: 1433
          DB_USERNAME: SA
          DB_PASSWORD: S3c0r3P4ss
          DB_DATABASE: cms
      - image: mcr.microsoft.com/mssql/server:2017-latest
        environment:
          SA_PASSWORD: S3c0r3P4ss
          ACCEPT_EULA: Y
    steps:
      - checkout
      - restore_cache:
          keys:
            - php82-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php82-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: echo "CREATE DATABASE cms;" > sqlserver.sql; for i in `seq 1 10`; do /opt/mssql-tools/bin/sqlcmd -S 127.0.0.1 -U SA -P 'S3c0r3P4ss' -i sqlserver.sql && exit 0; sleep 3; done
      - run: ./vendor/bin/phpunit

  "php85-sqlite":
    docker:
      - image: aimeos/ci-php:8.5
        environment:
          DB_DRIVER: sqlite
    steps:
      - checkout
      - restore_cache:
          keys:
            - php85-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php85-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: ./vendor/bin/phpunit

  "php85-mariadb":
    docker:
      - image: aimeos/ci-php:8.5
        environment:
          DB_DRIVER: mariadb
          DB_HOST: "127.0.0.1"
          DB_PORT: 3306
          DB_USERNAME: pagible
          DB_PASSWORD: pagible
          DB_DATABASE: cms
      - image: mariadb:latest
        environment:
          MARIADB_ROOT_PASSWORD: rootpw
          MARIADB_USER: pagible
          MARIADB_PASSWORD: pagible
          MARIADB_DATABASE: cms
    steps:
      - checkout
      - restore_cache:
          keys:
            - php85-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php85-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: for i in `seq 1 10`; do nc -z 127.0.0.1 3306 && echo OK && exit 0; echo -n .; sleep 1; done
      - run: ./vendor/bin/phpunit

  "php85-mysql":
    docker:
      - image: aimeos/ci-php:8.5
        environment:
          DB_DRIVER: mysql
          DB_HOST: "127.0.0.1"
          DB_PORT: 3306
          DB_USERNAME: pagible
          DB_PASSWORD: pagible
          DB_DATABASE: cms
      - image: mysql:latest
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_USER: pagible
          MYSQL_PASSWORD: pagible
          MYSQL_DATABASE: cms
    steps:
      - checkout
      - restore_cache:
          keys:
            - php85-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php85-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: for i in `seq 1 10`; do nc -z 127.0.0.1 3306 && echo OK && exit 0; echo -n .; sleep 1; done
      - run: ./vendor/bin/phpunit

  "php85-pgsql":
    docker:
      - image: aimeos/ci-php:8.5
        environment:
          DB_DRIVER: pgsql
          DB_HOST: "127.0.0.1"
          DB_PORT: 5432
          DB_USERNAME: pagible
          DB_PASSWORD: pagible
          DB_DATABASE: cms
      - image: postgres:18
        environment:
          POSTGRES_PASSWORD: pagible
          POSTGRES_USER: pagible
          POSTGRES_DB: cms
    steps:
      - checkout
      - restore_cache:
          keys:
            - php85-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php85-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: for i in `seq 1 10`; do nc -z 127.0.0.1 5432 && echo OK && exit 0; echo -n .; sleep 1; done
      - run: ./vendor/bin/phpunit

  "php83-mssql":
    docker:
      - image: aimeos/ci-php:8.3
        environment:
          DB_DRIVER: sqlsrv
          DB_HOST: "127.0.0.1"
          DB_PORT: 1433
          DB_USERNAME: SA
          DB_PASSWORD: S3c0r3P4ss
          DB_DATABASE: cms
          DB_ENCRYPT: yes
          DB_TRUST_SERVER_CERTIFICATE: yes
      - image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
          SA_PASSWORD: S3c0r3P4ss
          ACCEPT_EULA: Y
    steps:
      - checkout
      - restore_cache:
          keys:
            - php83-{{ checksum "composer.json" }}
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php83-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: echo "CREATE DATABASE cms;" > sqlserver.sql; for i in `seq 1 10`; do /opt/mssql-tools/bin/sqlcmd -C -S 127.0.0.1 -U SA -P 'S3c0r3P4ss' -i sqlserver.sql && exit 0; sleep 3; done
      - run: ./vendor/bin/phpunit

workflows:
  version: 2
  unittest:
    jobs:
      - "php82-mssql17"
#      - "php82-sqlite3"
#      - "php82-mariadb10"
#      - "php82-mysql8"
#      - "php82-pgsql14"
      - "php83-mssql"
#      - "php85-sqlite"
#      - "php85-mariadb"
#      - "php85-mysql"
#      - "php85-pgsql"
